name: onlineklein
favicon: null
layout_spectrum: 0.6067255914676934
typography_spectrum: 0.26999497623182833
title: a collection of random crap to test the grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.06883698026649654
  lightness: 0.1224127730820328
  saturation: 0.9992339946329594
  rhythmicContrast: 0.002748912898823619
purpose: []
